server:
  port: ${PORT:8080}

spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
#    jpa:
#      database-platform: org.hibernate.dialect.H2Dialect
    platform: org.hibernate.dialect.H2Dialect
    initialization-mode: embedded